import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-hidden bg-[#E2CCB1] bg-cover h-[100vh] w-[50vw] mx-auto font-['ThorneShaded']">
        <Header href="searchList" buttonText="Movies List" />
        <Hero />
      </div>
    </>
  );
}
